[env]
RUST_TARGET_PATH={value="./targets",relative = true}

[unstable]
build-std=["core","alloc"]

[source]
# crates-io = { replace-with = "vendored-sources" }
vendored-sources = { directory = "vendor" }