[package]
name = "phantomos-init"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
stivale-boot = "0.2.6"
std = { path = "../phantomos-kernel-std" }

[lib]
crate-type = ["cdylib"]

