[package]
name = "phantom-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phantom-panic-halt={path="../phantom-panic-halt"}

[lib]
crate-type=["staticlib"]